# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
## See https://github.com/metacran/r-builder for details.
## settings from edzer/gstat

language: R		 
sudo: required
cache: packages	

warnings_are_errors: false

env:
  global:
    - R_CHECK_ARGS = "--no-tests"
    
r_github_packages: 
  - hadley/devtools
  - jimhester/covr
    
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  ## saga and grass need to be installed from source and not using ubuntugis
  # install qgis and qgis-plugin-grass from 'ubuntugis'
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev qgis python-qgis qgis-plugin-grass

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG#rqgis
    
after_success:
  - Rscript -e 'covr::codecov()'





