# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r		 
cache:
  - ccache
  - packages	

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - libudunits2-dev
      - python-gdal
      - saga
      - equivs

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      latex: false
      env: qgis218=true
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      script: R -q -e 'tic::script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
          provider: script
          script: R -q -e 'tic::deploy()'
          on:
            branches: master
            condition:
               - $TRAVIS_PULL_REQUEST = false
               - $TRAVIS_EVENT_TYPE != cron
          
      after_deploy: R -q -e 'tic::after_deploy()'
      after_script: R -q -e 'tic::after_script()'
      after_success: R -q -e 'tic::after_success()'

    ### build QGIS LTR on macOS
    - os: osx
      osx_image: xcode8.3
      latex: false
      sudo: false
      env: OLD_LTR_mac=true
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      script: R -q -e 'tic::script()'
    ### build QGIS DEV on macOS
    - os: osx
      osx_image: xcode8.3
      latex: false
      sudo: false
      env: LTR_mac=true
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      script: R -q -e 'tic::script()'

# if we install everything from ubuntugis-unstable PPA, we get GDAL2 but only QGIS 2.14.X for trusty
# if we install everything from qgis.org/ubuntugis-ltr, we get most recent QGIS but missing GDAL2

before_install:
  - if [[ "${qgis218}" ]]; then sudo sh -c 'echo "deb http://qgis.org/ubuntugis-ltr trusty main" >> /etc/apt/sources.list'; fi
  - if [[ "${qgis218}" ]]; then sudo sh -c 'echo "deb-src http://qgis.org/ubuntugis-ltr trusty main " >> /etc/apt/sources.list'; fi
  
  - if [[ "${LTR_Linux}" ]]; then sudo sh -c 'echo "deb http://qgis.org/ubuntugis trusty main" >> /etc/apt/sources.list'; fi
  - if [[ "${LTR_Linux}" ]]; then sudo sh -c 'echo "deb-src http://qgis.org/ubuntugis trusty main " >> /etc/apt/sources.list'; fi
  
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -O - http://qgis.org/downloads/qgis-2017.gpg.key | gpg --import; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then gpg --fingerprint CAEB3DC3BDF7FB45 && gpg --export --armor CAEB3DC3BDF7FB45 | sudo apt-key add -; fi
  
  # we need to fake gdal-abi-2-1-3 as qgis won't find it otherwise because it searches for gdal20
  # see https://gis.stackexchange.com/questions/216780/cannot-install-qgis-2-18-from-repository-on-debian-stretch-package-gdal-abi-2
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then chmod ugo+x inst/travis/gdal-abi.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ./inst/travis/gdal-abi.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo equivs-build gdal-abi.control && sudo sudo dpkg -i gdal-abi-2-1-0_2.1.0_all.deb && sudo rm -rf gdal-abi-2-1-0_2.1.0_all.deb && sudo rm -rf gdal-abi.control; fi
    
  # install latest qgis-ltr using aptitude to resolve dependencies
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo aptitude install -y qgis python-qgis; fi  
  
  #############
  # OSX
  #############
  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  # make directory writable for osgeo4mac installations
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo chown -R $(whoami) /usr/local; fi
  
  # account for conflicting numpy installations https://github.com/travis-ci/travis-ci/issues/6688
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip2 uninstall numpy; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install numpy; fi
  
  # tap osgeo4mac tap
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew tap osgeo/osgeo4mac; fi
   
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install saga-gis-lts && brew install proj; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install python@2; fi
  
  # install required python packages
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then pip2 install --user psycopg2 matplotlib pyparsing gdal pyyaml jinja2 owslib pygments; fi
  # install qgis
  - if [[ "${OLD_LTR_mac}" ]]; then brew cask uninstall --force oclint && sudo rm -rf /usr/local/gfortran/bin/gfortran && brew install grass7 && brew unlink grass7 && brew install qgis2-ltr; fi
  - if [[ "${LTR_mac}" ]]; then brew cask uninstall --force oclint && sudo rm -rf /usr/local/gfortran/bin/gfortran && brew install grass7 && brew unlink grass7 && brew install qgis2; fi
  
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew link --overwrite --force gdal2; fi
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
  
# imitate a X virtual display -> https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start
  
notifications:
  slack:
      rooms:
        - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG #rqgis
  on_success: change # default: always
  on_failure: change # default: always
  email: false
