# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
## See https://github.com/metacran/r-builder for details.
## settings from edzer/gstat

language: R		 
sudo: required
cache: packages	
dist: trusty

warnings_are_errors: false

env:
  global:
    - R_CHECK_ARGS = "--no-tests"
    
r_github_packages: 
  - hadley/devtools
  - jimhester/covr
    
before_install:
    # install most recent QGIS
    - sudo sh -c 'echo "deb http://qgis.org/debian xenial main" >> /etc/apt/sources.list'  
    - sudo sh -c 'echo "deb-src http://qgis.org/debian xenial main " >> /etc/apt/sources.list'  
    - wget -O - http://qgis.org/downloads/qgis-2016.gpg.key | gpg --import
    - gpg --fingerprint 073D307A618E5811
    - gpg --export --armor 073D307A618E5811 | sudo apt-key add -

    - sudo apt-get update && sudo apt-get install qgis python-qgis saga

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG#rqgis
    
after_success:
  - Rscript -e 'covr::codecov()'





