# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R		 
sudo: required
cache: 
  - packages	
  - /usr/local
dist: trusty

warnings_are_errors: false

r_github_packages:
  - jimhester/covr
    
before_install:
    
    # this will install gdal1 instead of gdal2 when calling after ubuntugis installation (SAGA from source needs gdal1?)
    - sudo apt-get install -y libgdal-dev libproj-dev 
    
    # - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo add-apt-repository ppa:ubuntugis/ppa --yes
    - sudo apt-get --yes --force-yes update -qq

    - sudo apt-get install --yes aptitude # aptitude ensures that dependencies are installed 
    - sudo aptitude install -y qgis python-qgis qgis-plugin-grass grass qgis-provider-grass
    
    # install SAGA 2.2.2 from source
    - cd && wget https://sourceforge.net/projects/saga-gis/files/SAGA%20-%202.2/SAGA%202.2.2/saga-2.2.2.tar.gz && tar xvzf saga-2.2.2.tar.gz && rm saga-2.2.2.tar.gz
    - sudo apt-get install libwxgtk3.0-dev libtiff5-dev libjasper-dev libexpat1-dev wx-common libexpat1-dev libogdi3.2-dev unixodbc-dev
    - cd saga-2.2.2 && sudo autoreconf -i > /dev/null && ./configure > /dev/null && make > /dev/null && sudo make install > /dev/null && export SAGA_MLB=/usr/local/lib/saga && export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - cd /home/travis/build/jannes-m/RQGIS
    # check for successfull installation
    - saga_cmd --version
    
# imitate a X virtual display -> https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
      rooms:
        - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG#rqgis
      rooms:
        - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG#rqgis
    
after_success:
  - Rscript -e 'covr::codecov()'

# inspect log of failing tests
after_failure: "cat /home/travis/build/jannes-m/RQGIS/RQGIS.Rcheck/00check.log"