# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap
  
# Adapt as necessary starting from here

# try installing qgis

before_build:
  - start "" /wait "https://cmake.org/files/v3.7/cmake-3.7.2-win64-x64.msi" /S
  - start "" /wait "http://cygwin.com/setup-x86_64.exe" /S
  - start "" /wait "http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe" /S
  - start "" /wait "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip" /S

build_script:
  - travis-tool.sh install_deps

# test_script:
  # - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
